[unstable]
bindeps = true
build-std-features = ["compiler-builtins-mem"]
build-std = ["core","alloc", "compiler_builtins"]

[target.'cfg(target_os = "none")']
rustflags = ["-C", "relocation-model=static"]

[build]
target = "x86_64-unknown-none"


