name: Rust

on:
  push:
    branches: [ "edition14" ]
  pull_request:
    branches: [ "edition14" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: rustup default nightly;rustup target add x86_64-unknown-none;rustup target add x86_64-unknown-uefi; rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu;python build.py -b 
      
